### PR TITLE
add protocol property access

### PR DESCRIPTION
**Pull request by sjungwirth**

### CODE REVIEW

**Comment by thebearingedge** [comment]
Do you think it would be a good idea to ensure the `':'` in the protocol? `url-parse` itself doesn't seem to.

``` javascript
location.protocol = 'https';
```

gives us this:

``` bash
+ expected - actual

      -https//example.com:3000/foo?bar=baz#qux
      +https://example.com:3000/foo?bar=baz#qux
```

Also thanks for the PR!

**Comment by thebearingedge** [comment]
I bring this up because, at least from the console, setting `protocol` to `'https:'` in FireFox to throws an error but just setting it to `'https'` seems to work fine in Chrome, Firefox and IE 11.

**Comment by sjungwirth** [comment]
This fixed the specific problem I was having, I'll take a closer look
tomorrow.

**Comment by sjungwirth** [comment]
The docs and code for url-parse looks like it includes the `:` in protocol, https://www.npmjs.com/package/url-parse
Also in my testing I get a colon, how are you testing?

**Comment by thebearingedge** [comment]
Omitting `:` from the new protocol is failing for me.

``` javascript
it('should update the protocol', function () {

  location.protocol = 'https';

  expect(location.protocol)
    .to.equal('https:'); // actual - "https"
});

it('should update the full url', function () {

  location.protocol = 'https';

  expect(location.href)
    .to.equal('https://example.com:3000/foo?bar=baz#qux');
  // actual - "https//example.com:3000/foo?bar=baz#qux"
});
```

In your testing were you explicitly setting `protocol` with a `:`?

**Comment by sjungwirth** [comment]
I see, sure let me add that. I was just doing read access.

**Comment by sjungwirth** [comment]
fixed, also added `port` property access

**Comment by thebearingedge** [comment]
radical, thank you.

**Comment by sjungwirth** [comment]
Cool, do you think you could make a new npm version too? :smile:

**Comment by thebearingedge** [comment]
Yes, will do asap. Things are bad at work right now :(

**Comment by thebearingedge** [comment]
Done, I also added you to the repo collaborators. What's your npm handle?

**Comment by sjungwirth** [comment]
sjungwirth

**Pull request merged**
